### ISSUE TITLE
0/1 Knapsack

### ISSUE THREAD

**Issue by Bijoy-007** [khusw/algorithmBasic#1]

**Comment by Bijoy-007** [comment]
can I do this?

**Comment by khusw** [comment]
yes

**Comment by Bijoy-007** [comment]
please assign this to me

**Comment by khusw** [comment]
@Bijoy-007  I sent invitation, check it out

**Comment by Bijoy-007** [comment]
Hello I am making a pull request please accept it on or after 1st oct

**Comment by khusw** [comment]
I have created guidelines in the "README.md" file, and even if it is annoying, I would like you to rename the file according to this guideline.
I also want you to change file's location.
thanks.

**Comment by Bijoy-007** [comment]
But what should i put in site name?
